

export const CHECKLIST_ALPHA = [
  { section: '🚗 Véhicule', items: [
    { id:'fuel', label:'Carburant', type:'fuel', required:true },
    { id:'phares', label:'Phares', type:'ok_nok', required:true },
    { id:'clignotants', label:'Clignotants', type:'ok_nok', required:true },
    { id:'feux_bleus', label:'Feux bleus', type:'ok_nok', required:true },
    { id:'feux_travail', label:'Feux de travail', type:'ok_nok', required:true },
    { id:'eclairage_cab', label:'Éclairage cabine sanitaire', type:'ok_nok', required:true },
    { id:'huile', label:"Niveau d'huile moteur", type:'ok_insuf', required:true },
    { id:'refroid', label:'Niveau liquide de refroidissement', type:'ok_insuf', required:true },
    { id:'freins', label:'Niveau liquide de freins', type:'ok_insuf', required:true },
    { id:'lave_glace', label:'Niveau lave-glace', type:'ok_insuf', required:true },
    { id:'pneus_av', label:'État des pneus avant', type:'pneus', required:true },
    { id:'pneus_ar', label:'État des pneus arrière', type:'pneus', required:true },
  ]},
  { section: '🧹 Propreté', items: [
    { id:'carrosserie', label:'Carrosserie', type:'propre_sale', required:true },
    { id:'cab_chauffeur', label:'Cabine chauffeur', type:'propre_sale', required:true },
    { id:'cab_sanitaire', label:'Cabine sanitaire', type:'propre_sale', required:true },
    { id:'poubelle', label:'Poubelle', type:'vide_pleine', required:true },
  ]},
  { section: '🧰 Équipement', items: [
    { id:'extincteur', label:'Extincteur', type:'ok_nok', required:true },
    { id:'boite_secours', label:'Boîte de secours', type:'ok_nok', required:true },
    { id:'triangle', label:'Triangle', type:'ok_nok', required:true },
    { id:'marteau', label:'Marteau brise-vitre', type:'ok_nok', required:true },
    { id:'radio_fixe', label:'Radio fixe', type:'ok_nok_np', required:true },
    { id:'radio_port', label:'Radio portative', type:'ok_nok_np', required:true },
    { id:'marchepied', label:'Marchepied', type:'ok_nok_np', required:true },
    { id:'draps', label:'Sets de draps x3', type:'ok_nok', required:true },
    { id:'toile_glisse', label:'Toile de glisse', type:'ok_nok', required:true },
  ]},
  { section: '📄 Documents', items: [
    { id:'cert_conf', label:'Certificat de conformité', type:'ok_nok', required:true },
    { id:'immat', label:"Certificat d'immatriculation", type:'ok_nok', required:true },
    { id:'assurance', label:'Assurance', type:'ok_nok', required:true },
    { id:'ct', label:'Contrôle technique', type:'date', required:true },
    { id:'constat', label:"Constat d'accident", type:'ok_nok', required:true },
    { id:'carnet_bord', label:'Carnet de bord', type:'ok_nok', required:true },
    { id:'bon_transport', label:'Bon de transport', type:'ok_nok', required:true },
    { id:'carte_carb', label:'Carte carburant', type:'ok_nok', required:false },
    { id:'suivi_hygiene', label:"Suivi d'hygiène", type:'ok_nok', required:false },
    { id:'farde_listing', label:'Farde listing hôpitaux', type:'ok_nok', required:false },
    { id:'farde_sceller', label:'Farde scellée', type:'ok_nok', required:false },
  ]},
  { section: "🏥 Cartes d'accès hôpitaux", items: [
    { id:'h_epicura', label:'Epicura', type:'ok_nok', required:false },
    { id:'h_chwapi', label:'Chwapi', type:'ok_nok', required:false },
    { id:'h_chm', label:'CHM', type:'ok_nok', required:false },
    { id:'h_glorieux', label:'AZ Glorieux', type:'ok_nok', required:false },
  ]},
  { section: '🔬 Paramètres médicaux', items: [
    { id:'pulsox', label:'Pulsoxymètre', type:'ok_nok_np', required:false },
    { id:'tensio', label:'Tensiomètre', type:'ok_nok_np', required:false },
    { id:'gluco', label:'Glucomètre', type:'ok_nok_np', required:false },
    { id:'thermo_auri', label:'Thermomètre auriculaire', type:'ok_nok_np', required:false },
    { id:'thermo_digit', label:'Thermomètre digital', type:'ok_nok_np', required:true },
  ]},
  { section: '🫁 Oxygènes', items: [
    { id:'o2_b2_1', label:'B2 (1)', type:'o2', required:true },
    { id:'o2_b2_2', label:'B2 (2)', type:'o2', required:true },
    { id:'o2_b10_1', label:'B10 (1)', type:'o2', required:true },
    { id:'o2_b10_2', label:'B10 (2)', type:'o2', required:true },
  ]},
  { section: '📝 Fin de checklist', items: [
    { id:'km', label:'Kilométrage', type:'number', required:true },
    { id:'remarques', label:'Remarques / Problèmes', type:'textarea', required:false },
    { id:'nom1', label:'Ambulancier 1', type:'text', required:true },
    { id:'nom2', label:'Ambulancier 2', type:'text', required:false },
  ]},
]

export const CHECKLIST_TPMR = [
  { section: '🚗 Véhicule', items: [
    { id:'fuel', label:'Carburant', type:'fuel', required:true },
    { id:'phares', label:'Phares', type:'ok_nok', required:true },
    { id:'clignotants', label:'Clignotants', type:'ok_nok', required:true },
    { id:'huile', label:"Niveau d'huile moteur", type:'ok_insuf', required:true },
    { id:'refroid', label:'Niveau liquide de refroidissement', type:'ok_insuf', required:true },
    { id:'freins', label:'Niveau liquide de freins', type:'ok_insuf', required:true },
    { id:'lave_glace', label:'Niveau lave-glace', type:'ok_insuf', required:true },
    { id:'pneus_av', label:'État des pneus avant', type:'pneus', required:true },
    { id:'pneus_ar', label:'État des pneus arrière', type:'pneus', required:true },
  ]},
  { section: '🧹 Propreté', items: [
    { id:'carrosserie', label:'Carrosserie', type:'propre_sale', required:true },
    { id:'interieur', label:'Intérieur', type:'propre_sale', required:true },
  ]},
  { section: '🧰 Équipement', items: [
    { id:'fauteuil', label:'Fauteuil roulant', type:'ok_nok_np', required:true },
    { id:'sangle', label:'Sangle fauteuil', type:'ok_nok', required:true },
    { id:'extincteur', label:'Extincteur', type:'ok_nok', required:true },
    { id:'triangle', label:'Triangle', type:'ok_nok', required:true },
    { id:'boite_secours', label:'Boîte de secours', type:'ok_nok', required:true },
    { id:'sac_secours', label:'Sac de secours', type:'ok_nok', required:true },
    { id:'radio_port', label:'Radio portative', type:'ok_nok_np', required:true },
  ]},
  { section: '📄 Documents', items: [
    { id:'cert_conf', label:'Certificat de conformité', type:'ok_nok', required:true },
    { id:'immat', label:"Certificat d'immatriculation", type:'ok_nok', required:true },
    { id:'assurance', label:'Assurance', type:'ok_nok', required:true },
    { id:'ct', label:'Contrôle technique', type:'date', required:true },
    { id:'constat', label:"Constat d'accident", type:'ok_nok', required:true },
    { id:'carnet_bord', label:'Carnet de bord', type:'ok_nok', required:true },
    { id:'bon_transport', label:'Bon de transport', type:'ok_nok', required:true },
    { id:'carte_carb', label:'Carte carburant', type:'ok_nok', required:false },
    { id:'farde_listing', label:'Farde listing hôpitaux', type:'ok_nok', required:true },
    { id:'farde_sceller', label:'Farde scellée', type:'ok_nok', required:true },
  ]},
  { section: "🏥 Cartes d'accès hôpitaux", items: [
    { id:'h_epicura', label:'Epicura', type:'ok_nok', required:true },
    { id:'h_chm', label:'CHM', type:'ok_nok', required:true },
  ]},
  { section: '📝 Fin de checklist', items: [
    { id:'km', label:'Kilométrage', type:'number', required:true },
    { id:'remarques', label:'Remarques / Problèmes', type:'textarea', required:false },
    { id:'nom1', label:'Nom du chauffeur', type:'text', required:true },
  ]},
]

export const CHECKLIST_VSL = [
  { section: '🚗 Véhicule', items: [
    { id:'fuel', label:'Carburant', type:'fuel', required:true },
    { id:'phares', label:'Phares', type:'ok_nok', required:true },
    { id:'clignotants', label:'Clignotants', type:'ok_nok', required:true },
    { id:'huile', label:"Niveau d'huile moteur", type:'ok_insuf', required:true },
    { id:'refroid', label:'Niveau liquide de refroidissement', type:'ok_insuf', required:true },
    { id:'freins', label:'Niveau liquide de freins', type:'ok_insuf', required:true },
    { id:'lave_glace', label:'Niveau lave-glace', type:'ok_insuf', required:true },
    { id:'pneus_av', label:'État des pneus avant', type:'pneus', required:true },
    { id:'pneus_ar', label:'État des pneus arrière', type:'pneus', required:true },
  ]},
  { section: '🧹 Propreté', items: [
    { id:'carrosserie', label:'Carrosserie', type:'propre_sale', required:true },
    { id:'interieur', label:'Intérieur', type:'propre_sale', required:true },
  ]},
  { section: '🧰 Équipement', items: [
    { id:'fauteuil', label:'Fauteuil roulant', type:'ok_nok_np', required:true },
    { id:'sangle', label:'Sangle fauteuil', type:'ok_nok', required:true },
    { id:'extincteur', label:'Extincteur', type:'ok_nok', required:true },
    { id:'triangle', label:'Triangle', type:'ok_nok', required:true },
    { id:'boite_secours', label:'Boîte de secours', type:'ok_nok', required:true },
    { id:'radio_port', label:'Radio portative', type:'ok_nok_np', required:true },
  ]},
  { section: '📄 Documents', items: [
    { id:'cert_conf', label:'Certificat de conformité', type:'ok_nok', required:true },
    { id:'immat', label:"Certificat d'immatriculation", type:'ok_nok', required:true },
    { id:'assurance', label:'Assurance', type:'ok_nok', required:true },
    { id:'ct', label:'Contrôle technique', type:'date', required:true },
    { id:'constat', label:"Constat d'accident", type:'ok_nok', required:true },
    { id:'carnet_bord', label:'Carnet de bord', type:'ok_nok', required:true },
    { id:'bon_transport', label:'Bon de transport', type:'ok_nok', required:true },
    { id:'carte_carb', label:'Carte carburant', type:'ok_nok', required:false },
    { id:'farde_listing', label:'Farde listing hôpitaux', type:'ok_nok', required:true },
    { id:'farde_sceller', label:'Farde scellée', type:'ok_nok', required:true },
  ]},
  { section: "🏥 Cartes d'accès hôpitaux", items: [
    { id:'h_epicura', label:'Epicura', type:'ok_nok', required:true },
  ]},
  { section: '📝 Fin de checklist', items: [
    { id:'km', label:'Kilométrage', type:'number', required:true },
    { id:'remarques', label:'Remarques / Problèmes', type:'textarea', required:false },
    { id:'nom1', label:'Nom du chauffeur', type:'text', required:true },
  ]},
]
